services:
  - type: web
    name: north-code-play
    env: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    region: oregon
    branch: main
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
